//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace RaceYourself.Models
{
    public class Invite
    {
        public string code;
        public DateTime? expires_at;
        public DateTime? used_at;
        public string user_id;
        public string identity_type;
        public string identity_uid;

        public Invite () {}

    }
}

