//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace RaceYourself.Models
{
    public class InviteAction
    {
        public string action;
        public string provider;
        public string uid;
        public string code;

        public InviteAction() {}
        public InviteAction (string action, string provider, string uid, string code)
        {
            this.action = action;
            this.provider = provider;
            this.uid = uid;
            this.code = code;
        }
    }
}

